name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

  workflow_dispatch:

jobs:

  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Project
        run: pip install '.[test]'
      - name: Run Lint
        run: pflake8
      - name: Run isort check
        run: isort --check --diff dundie tests integration
      - name: Run Black check
        run: black --check --diff dundie tests integration

  test:
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Project
        run: pip install '.[test]'
      - name: Run Tests
        run: make testcicd
      - name: publish junit results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: test-result.xml
          check_name: Test Results (Python ${{ matrix.python-version }})
